#' Create RasterLayer object from \code{bfastSpatial()} output
#'
#' This function formats tabular data into a RasterLayer.
#'
#' @param cell A character with the name of the field in \code{data} containing
#'   the cell numbers.
#' @param variable A character with the name of the field in \code{data}
#'   containing the variable to be set as the pixel values in the raster.
#' @param data The data frame containing \code{cell} and \code{variable}.
#' @param template A Raster object with the same extent, resolution, and
#'   projection as the raster dataset used to generate \code{data}.
#'   Alternatively, the path to an XML file generated by
#'   \code{create_raster_metadata}.
#' @param no_data A numeric value to fill in the rest of the returned
#'   RasterLayer object where no value is specified. The default is \code{NA}.
#' @return A RasterLayer object containing the specified pixel values.
#' @examples
#' \dontrun{
#' create_raster(no_cell, total_breaks, bfast_data_frame, template)
#' }
#' @export
create_raster <- function(cell, variable, data, template, no_data=NA) {
  template <- create_template_raster(template)
  value <- rep(no_data, times=ncell(template))
  value[data[,cell]] <- data[,variable]
  mat <- matrix(data=value, nrow=nrow(template), ncol=ncol(template), byrow=TRUE)
  return(raster(x=mat, template=template))
}
