#' Create a date vector from \code{MODIStsp}-generated RasterStack
#'
#' This function creates a vector of class Date that corresponds to the
#' observations in MODIS data processed by \code{MODIStsp}.
#'
#' The output of this function is most useful for passing as an argument to
#' \code{bfastSpatial()}, which requires a date vector.
#'
#' @param stack A RasterStack object generated by \code{MODIStsp()}.
#' @return A vector of class Date containing the dates for each raster layer.
#' @examples
#' \dontrun{
#' MODIStsp_date(raster_stack)
#' }
#' @importFrom dplyr mutate
#' @importFrom magrittr %>%
#' @export
MODIStsp_date <- function(stack) {
  ras.names <- names(stack)
  dates.df <- data.frame(jul=gsub("^MOD[[:alnum:]]+_[[:alnum:]]+_", "", ras.names)) %>%
    mutate(year=as.numeric(extractMatches(jul, "^[[:digit:]]{4}")), num.date=as.numeric(extractMatches(jul, "[[:digit:]]{3}$"))) %>%
    mutate(date=base::as.Date(num.date, origin=base::as.Date(paste(year-1, "12", "31", sep="-"))))
  return(dates.df[,"date"])
}
